trigger:
  batch: true
  branches:
    include:
      - main

pr:
  - main

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: "hmcts"

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentImage
    value: ubuntu-24.04
  - name: serviceConnection
    value: "DTS-SHAREDSERVICESPTL-SBOX"
  - name: baseDirectory
    value: example
  - name: product
    value: "core"
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries


parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy
  - name: deploy_example
    type: boolean
    default: false
  - name: environment_components
    type: object
    default:
      - deployment: 'example'
        terraformInitSubscription: 'DTS-SHAREDSERVICESPTL-SBOX'


stages:
  - stage: Precheck
    jobs:
      - job: PrecheckJob
        pool:
          vmImage: ${{ variables.agentImage }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: "infra-vault-nonprod"
              keyvaultSecret: "azure-devops-sp-token"
              serviceConnection: "azurerm-sandbox"
              overrideAction: "plan"
              forcePreventParallelJobRun: true

  - ${{ if parameters.deploy_example }}:
    - stage: TerraformDeployment
      dependsOn: Precheck
      jobs:
        - job: DeployExample
          timeoutInMinutes: ${{ variables.timeoutInMinutes }}
          pool:
            vmImage: ${{ variables.agentImage }}
          steps:
            - template: steps/terraform.yaml@cnp-azuredevops-libraries
              parameters:
                overrideAction: ${{ parameters.overrideAction }}
                serviceConnection: ${{ variables.serviceConnection }}
                environment: 'sandbox'
                component: ''
                terraformInitSubscription: '04d27a32-7a07-48b3-95b8-3c8691e1a263' #HMCTS-CONTROL
                product: ${{ variables.product }}
                baseDirectory: ${{ variables.baseDirectory }}
                backendResourceGroupName: 'azure-control-ptlsbox-rg'
                tfVarsFile: "example.tfvars"

  - stage: Test
    dependsOn: Precheck
    jobs:
      - job: TerraformTest
        pool:
          vmImage: ${{ variables.agentImage }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        workspace:
          clean: all
        steps:
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'
          - task: AzureCLI@2
            inputs:
              azureSubscription: "DTS-SHAREDSERVICESPTL-SBOX"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                terraform init
                terraform test